Movie_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from movie_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie_app/', include('movie_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_app/urls.py
from django.urls import path

from .views import IndexView, ConfirmationView, UserRegisterView, UserLoginView, UserLogoutView, UserActiveAccountView, \
    UserUpdateView, UserPasswordUpdateView, UserPasswordResetView, UserPasswordSetView, UserDeleteView, UserMovieView, \
        UserMoviesView, UserPersonView, UserPersonsView, UserCommentsView, UserCommentDeleteView, GenreCreateView, \
            GenreUpdateView, GenreDeleteView, GenreListView, PersonCreateView, PersonUpdateView, PersonDeleteView, \
                PersonDetailView, PersonMoviesView, PersonListView, MovieCreateView, MovieUpdateView, MovieDeleteView, \
                    MovieDetailView, MoviePersonsView, MovieCommentsView, MovieListView, ContactView
                


urlpatterns = [
    path('', view=IndexView.as_view(), name='index'),
    path('confirmation', view=ConfirmationView.as_view(), name='confirmation'),
    path('user_register', view=UserRegisterView.as_view(), name='user-register'),
    path('user_login', view=UserLoginView.as_view(), name='user-login'),
    path('user_logout', view=UserLogoutView.as_view(), name='user-logout'),
    path('user_active_account', view=UserActiveAccountView.as_view(), name='user-active-account'),
    path('user_update', view=UserUpdateView.as_view(), name='user-update'),
    path('user_password_update', view=UserPasswordUpdateView.as_view(), name='user-password-update'),
    path('user_password_reset', view=UserPasswordResetView.as_view(), name='user-password-reset'),
    path('user_password_set', view=UserPasswordSetView.as_view(), name='user-password-set'),
    path('user_delete', view=UserDeleteView.as_view(), name='user-delete'),
    path('user_movie/<int:pk>', view=UserMovieView.as_view(), name='user-movie'),
    path('user_movies', view=UserMoviesView.as_view(), name='user-movies'),
    path('user_person/<int:pk>', view=UserPersonView.as_view(), name='user-person'),
    path('user_persons', view=UserPersonsView.as_view(), name='user-persons'),
    path('user_comments', view=UserCommentsView.as_view(), name='user-comments'),
    path('user_comment_delete/<int:pk>', view=UserCommentDeleteView.as_view(), name='user-comment-delete'),
    path('genre_create', view=GenreCreateView.as_view(), name='genre-create'),
    path('genre_update/<int:pk>', view=GenreUpdateView.as_view(), name='genre-update'),
    path('genre_delete/<int:pk>', view=GenreDeleteView.as_view(), name='genre-delete'),
    path('genre_list', view=GenreListView.as_view(), name='genre-list'),
    path('person_create', view=PersonCreateView.as_view(), name='person-create'),
    path('person_update/<int:pk>', view=PersonUpdateView.as_view(), name='person-update'),
    path('person_delete/<int:pk>', view=PersonDeleteView.as_view(), name='person-delete'),
    path('person_detail/<int:pk>', view=PersonDetailView.as_view(), name='person-detail'),
    path('person_movies/<int:pk>/<str:status>', view=PersonMoviesView.as_view(), name='person-movies'),
    path('person_list', view=PersonListView.as_view(), name='person-list'),
    path('movie_create/', MovieCreateView.as_view(), name='movie-create'),
    path('movie_update/<int:pk>', view=MovieUpdateView.as_view(), name='movie-update'),
    path('movie_delete/<int:pk>', view=MovieDeleteView.as_view(), name='movie-delete'),
    path('movie_detail/<int:pk>', view=MovieDetailView.as_view(), name='movie-detail'),
    path('movie_persons/<int:pk>', view=MoviePersonsView.as_view(), name='movie-persons'),
    path('movie_comments/<int:pk>', view=MovieCommentsView.as_view(), name='movie-comments'),
    path('movie_list', view=MovieListView.as_view(), name='movie-list'),
    path('contact', view=ContactView.as_view(), name='contact'),
]

movie_app/models.py
import uuid

from pathlib import Path

from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import AbstractUser

from django_resized import ResizedImageField
from django_countries.fields import CountryField

from .validators import validate_year, validate_rating

# Create your models here.

def image_upload_handler(instance, filename):
    
    model_name = instance.__class__.__name__
    uuid_code = str(uuid.uuid1()).replace('-', '')[:8]
    file_suffix = Path(filename).suffix
    new_filename = f'{instance}_{uuid_code}'
    
    return f'movie_app/{model_name}/{new_filename}{file_suffix}'


class User(AbstractUser):

    class Meta:
            verbose_name = 'Użytkownik'
            verbose_name_plural = 'Użytkownicy'

    first_name = models.CharField(verbose_name='Imię', max_length=64)
    last_name = models.CharField(verbose_name='Nazwisko', max_length=64)
    is_active = models.BooleanField(verbose_name='Aktywny', default=False)
    username = models.CharField(
        verbose_name='Nazwa użytkownika',
        max_length=64,
        unique=True,
        error_messages={'unique': 'Nazwa użytkownika już zarejestrowana w serwisie'},
        )
    email = models.EmailField(
        verbose_name='Email',
        max_length=255,
        unique=True,
        error_messages={'unique': 'Email już zarejestrowany w serwisie'},
        )
    avatar = ResizedImageField(
        size=[192, 256],
        crop=['middle', 'center'],
        force_format='PNG',
        upload_to=image_upload_handler,
        default='movie_app/default_person.png',
        verbose_name='Awatar'
        )
    
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):

        return self.username
    
    def get_full_name(self):
        
        return f'{self.first_name} {self.last_name}'

    def email_user(self, subject, message, from_email='webmaster@localhost', *args, **kwargs):
        
        send_mail(subject, message, from_email, [self.email,], *args, **kwargs)


class UserUniqueToken(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    token = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

class Person(models.Model):

    class Meta:
        verbose_name = 'Postać'
        verbose_name_plural = 'Postacie'
        unique_together = ['first_name', 'last_name']
        ordering = ['first_name', 'last_name']

    first_name = models.CharField(max_length=32, verbose_name='Imię')
    last_name = models.CharField(max_length=32, verbose_name='Nazwisko')
    date_of_birth = models.DateField(verbose_name='Data urodzenia')
    date_of_death = models.DateField(verbose_name='Data śmierci', null=True, blank=True)
    biography = models.TextField(verbose_name='Biografia', blank=True)
    country = CountryField(blank_label='Wybierz z listy', verbose_name='Kraj pochodzenia')
    liked_by = models.ManyToManyField(
        'User',
        related_name='liked_persons',
        verbose_name='Polubienia',
        blank=True
        )
    avatar = ResizedImageField(
        size=[192, 256],
        crop=['middle', 'center'],
        force_format='PNG',
        upload_to=image_upload_handler,
        default='movie_app/default_person.png',
        verbose_name='Awatar'
        )
    
    def __str__(self):

        return f'{self.first_name} {self.last_name}'

    def unique_error_message(self, model_class, unique_check):

        if unique_check == ('first_name', 'last_name'):
            return 'Postać już zapisana w serwisie'

        return super().unique_error_message(model_class, unique_check)


class Genre(models.Model):

    class Meta:
        verbose_name = 'Gatunek'
        verbose_name_plural = 'Gatunki'
        ordering = ['name']

    name = models.CharField(
        max_length=32,
        unique=True,
        error_messages={'unique':'Nazwa gatunku już zapisana w serwisie'},
        verbose_name='Nazwa'
        )
    
    def __str__(self):
        
        return self.name


class Movie(models.Model):

    class Meta:
        verbose_name = 'Film'
        verbose_name_plural = 'Filmy'
        ordering = ['-rating', 'title']

    title = models.CharField(max_length=128, verbose_name='Tytuł')
    duration = models.DurationField(verbose_name='Czas trwania')
    plot = models.TextField(verbose_name='Fabuła', blank=True)
    year = models.PositiveSmallIntegerField(verbose_name='Rok produkcji', validators=[validate_year])
    rating = models.DecimalField(verbose_name='Ranking', max_digits=3, decimal_places=1, validators=[validate_rating])
    director = models.ForeignKey(
        'Person',
        related_name='directors',
        verbose_name='Reżyseria',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
        )
    screenplay = models.ForeignKey(
        'Person',
        related_name='screenplays',
        verbose_name='Scenariusz',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
        )
    characters = models.ManyToManyField(
        'Person',
        related_name='characters',
        verbose_name='Aktorzy',
        through='Character',
        blank=True
        )
    comments = models.ManyToManyField(
        'User',
        related_name='comment_movies',
        verbose_name='Komentarze',
        through='Comment',
        blank=True
        )
    liked_by = models.ManyToManyField(
        'User',
        related_name='liked_movies',
        verbose_name='Polubienia',
        blank=True
        )
    genre = models.ManyToManyField(
        'Genre',
        related_name='genries',
        verbose_name='Gatunek',
        blank=True
        )
    avatar = ResizedImageField(
        size=[192, 256],
        crop=['middle', 'center'],
        force_format='PNG',
        upload_to=image_upload_handler,
        default='movie_app/default_movie.png',
        verbose_name='Awatar'
        )
    
    def __str__(self):
        
        return self.title


class Character(models.Model):

    class Meta:
        verbose_name = 'Postać w filmie'
        verbose_name_plural = 'Postacie w filmach'
        unique_together = ['person', 'movie']
        ordering = ['movie']
        
    role = models.CharField(max_length=128, verbose_name='Postac')
    person = models.ForeignKey(
        'Person',
        related_name='person_characters',
        verbose_name='Aktor',
        on_delete=models.CASCADE
        )
    movie = models.ForeignKey(
        'Movie',
        related_name='movie_characters',
        verbose_name='Film',
        on_delete=models.CASCADE
        )
    
    def __str__(self):

        return f'{self.person}, {self.movie}, {self.role}'
    
    def unique_error_message(self, model_class, unique_check):

        if unique_check == ('person', 'movie'):
            return f'Aktor już ma przypisaną rolę w tym filmie'

        return super().unique_error_message(model_class, unique_check)


class Comment(models.Model):

    class Meta:
        verbose_name = 'Komentarz'
        verbose_name_plural = 'Komentarze'
        unique_together = ['movie', 'user']
        ordering = ['-date_added']
        
    comment = models.TextField(verbose_name='Komentarz')
    date_added = models.DateTimeField(verbose_name='Data wpisu', auto_now_add=True)
    movie = models.ForeignKey(
        'Movie',
        related_name='movie_comments',
        verbose_name='Film',
        on_delete=models.CASCADE
        )
    user = models.ForeignKey(
        'User',
        related_name='user_comments',
        verbose_name='Użytkownik',
        on_delete=models.CASCADE
        )

    def __str__(self):

        return f'{self.movie}, {self.user}'
    
    def unique_error_message(self, model_class, unique_check):

        if unique_check == ('movie', 'user'):
            return f'Użytkownik już skomentował ten film'

        return super().unique_error_message(model_class, unique_check)

movie_app/templates/movie_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.4/tiny-slider.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.4/min/tiny-slider.helper.ie8.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.4/min/tiny-slider.js"></script>
    <link rel="stylesheet" href="{% static 'movie_app/css/style.css' %}">
</head>
<body>
    <div class="container-style">
        <header>
            <nav class="navbar navbar-style">
                <div>
                    <a href="{% url 'index' %}">
                        <img src="{% static 'movie_app/image/logo.png' %}" class="navbar-logo-style" alt="Logo">
                    </a>
                </div>
                <div>
                    <a href="{% url 'movie-list' %}" class="navbar-main-style">Filmy</a>
                    <a href="{% url 'person-list' %}" class="navbar-main-style">Postacie</a>
                </div>
                <div class="col d-flex justify-content-end">
                    <form action="{% url 'movie-list' %}" method="GET" class="navbar-form-style">
                        <input type="text" name="title" placeholder="Tytuł" value="">
                        <button type="submit">&#9740;</button>
                    </form>
                    <div class="nav-item dropdown navbar-dropdown-style">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-toggle font-size-1-25" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ request.user }}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                {% if request.user.is_staff %}
                                    <li><a href="{% url 'person-create' %}" class="dropdown-item">Nowy postać</a></li>
                                    <li><a href="{% url 'movie-create' %}" class="dropdown-item">Nowy film</a></li>
                                    <li><a href="{% url 'genre-list' %}" class="dropdown-item">Gatunki</a></li>
                                    <div class="dropdown-divider"></div>
                                {% endif %}
                                <li><a href="{% url 'user-movies' %}" class="dropdown-item">Moje filmy</a></li>
                                <li><a href="{% url 'user-persons' %}" class="dropdown-item">Moje postacie</a></li>
                                <li><a href="{% url 'user-comments' %}" class="dropdown-item">Komentarze</a></li>
                                <div class="dropdown-divider"></div>
                                <li><a href="{% url 'user-update' %}" class="dropdown-item">Edytuj konto</a></li>
                                <li><a href="{% url 'user-password-update' %}" class="dropdown-item">Zmień hasło</a></li>
                                <li><a href="{% url 'user-delete' %}" class="dropdown-item">Usuń konto</a></li>
                                <div class="dropdown-divider"></div>
                                <li><a href="{% url 'user-logout' %}" class="dropdown-item">Wyloguj</a></li>
                            </ul>
                        {% else %}
                            <a class="dropdown-toggle font-size-1-25" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Użytkownik
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a href="{% url 'user-login' %}" class="dropdown-item">Zaloguj</a></li>
                                <div class="dropdown-divider"></div>
                                <li><a href="{% url 'user-register' %}" class="dropdown-item">Rejestracja</a></li>
                            </ul>
                        {% endif  %}
                    </div>
                </div>
            </nav>
        </header>
        <section>
            <!-- //--------------------------- page content -------------------------// -->
            {% block content %}{% endblock content %}
            <!-- //--------------------------- page content end ---------------------// -->
        </section>
        <div class="footer-push-style"></div>
    </div>
    <div class="footer-style text-center">
        <div class="text-center p-3"><a href="{% url 'contact' %}">@ Formularz kontaktowy</a></div>
    </div>
    <script src="{% static 'movie_app/js/app.js' %}"></script> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

movie_app/templates/movie_app/genre_list.html
{% extends 'movie_app/base.html' %}
{% block content %}
<div class="row container-body-style">
    <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="container-header-style">
            Wszystkie gatunki filmów
        </div>
        <div class="container-card-style">
            <div class="row">
                <div class="col">
                    <ul class="list-float-style">
                        {% for genre in genre_list %}
                            <li>{{ genre }}
                                <a href="{% url 'genre-update' pk=genre.pk %}" title="Edytuj" class="font-size-1-25">&#9997;</a>
                                <a href="{% url 'genre-delete' pk=genre.pk %}" title="Usuń" class="text-danger font-size-1-25">&#10008;</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="row row-margin-styly">
                <div class="col right-style">
                    <a href="{% url 'genre-create' %}" class="btn button-style">Dodaj</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

movie_app/templates/movie_app/movie_comments.html
{% extends 'movie_app/base.html' %}
{% block content %}
<div class="row container-body-style">
    <div class="container-header-style">{{ movie }}</div>
    <div class="row">
        <div class="col-sm-2">
            <div class="container-image-style">
                <a href="{{ movie.avatar.url }}"><img src="{{ movie.avatar.url }}" alt="Avatar"></a>
            </div>
        </div>
        <div class="col-sm-10">
            <div class="container-card-style">
                <div class="font-size-1-5">
                    Komentarze ( {{ movie.comments.count }} )
                    <a href="{% url 'movie-detail' pk=movie.pk %}#comments" title="Wstecz">&#8679;</a>
                </div>
                <table class="table table-comment-style">
                    <tbody>
                        {% for comment in movie.movie_comments.all %}
                            <tr>
                                <td class="col-1"><img src="{{ comment.user.avatar.url }}" alt="Avatar"></td>
                                <td class="col-11">
                                    <div class="row comment-header-style">
                                        <div class="col-10">
                                            {{ comment.user }}, {{ comment.date_added|date:"j E Y, H:i"}}
                                        </div>
                                        <div class="col-2 right-style">
                                            {% if comment.user == request.user %}
                                                <a href="{% url 'user-comment-delete' pk=comment.pk %}?next={{ request.path }}#comments"
                                                class="text-danger" title="Usuń komentarz">&#10008;</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="text-comment-style">
                                        <span class="text-content">{{ comment.comment }}</span>
                                        <span class="text-hidden display-none"></span>
                                        <span class="dots display-none"> ...</span>
                                        <button class="button-more-style button-more display-none" title="Rozwiń tekst">&#8681;</button>
                                        <button class="button-more-style button-less display-none" title="Zwin tekst">&#8679;</button>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

movie_app/templates/movie_app/movie_persons.html
{% extends 'movie_app/base.html' %}
{% block content %}
<div class="row container-body-style">
    <div class="container-header-style">{{ movie }}</div>
    <div class="row">
        <div class="col-sm-2">
            <div class="container-image-style">
                <a href="{{ movie.avatar.url }}"><img src="{{ movie.avatar.url }}" alt="Avatar"></a>
            </div>
        </div>
        <div class="col-sm-10">
            <div class="container-card-style">
                <div class="font-size-1-5">
                    Aktorzy ( {{ movie.characters.count }} )
                    <a href="{% url 'movie-detail' pk=movie.pk %}#characters" title="Wstecz">&#8679;</a>
                </div>
                <table class="table table-style">
                    <tbody>
                        {% for character in movie.movie_characters.all %}
                            <tr>
                                <td class="col-1"><img src="{{ character.person.avatar.url }}" alt="Avatar"></td>
                                <td class="col-6">
                                    <ul class="list-none-style">
                                        <li><a href="{% url 'person-detail' pk=character.person.pk %}" class="font-size-1-25">{{ character.person }}</a></li>
                                        <li>Kraj pochodzenia:</li>
                                        <li>{{ character.person.country.name }}</li>
                                        </ul>
                                </td>
                                <td class="col-5 text-center">
                                    Postać:</br>{{ character.role }}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

movie_app/templates/movie_app/person_delete.html
{% extends 'movie_app/base.html' %}
{% block content %}
<div class="row container-body-style">
    <div class="col-lg-4 col-md-8 col-sm-12">
        <div class="container-header-style">
            Potwierdź usunięcie - {{ person }}
        </div>
        <div class="container-card-style">
            <form class="form-style" action="" method="POST">
                {% csrf_token %}
                <div class="row">
                    <p class="text-center text-danger">
                        <strong>Usuwając postać zostaje ona wykasowana z wszystkich filmów</strong>
                    </p>
                </div>
                <div class="row row-margin-style">
                    <div class="col-6">
                        <a href="{% url 'person-detail' pk=person.pk %}" class="btn button-style">Anuluj</a>
                    </div>
                    <div class="col-6 right-style">
                        <button type="submit" class="btn button-style">Potwierdź</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

movie_app/templates/movie_app/person_list.html
{% extends 'movie_app/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row container-body-style">
    <div class="col-lg-10 col-md-11 col-sm-12">
        <div class="row container-header-style">
            <div class="col-8 left-style">
                {% if search_count or search_count == 0 %}
                    Wyszukanych postaci: {{ search_count }}
                {% else %}
                    Wszystkie postacie
                {% endif %}
                <button type="button" class="button-more-style button-more" title="Rozwiń wyszukiwanie">&#8681;</button>
                <button type="button" class="button-more-style button-less display-none" title="Zwiń wyszukiwanie">&#8679;</button>
            </div>
            <div class="col-4 right-style">
                {% if is_paginated %}
                    {% if page_obj.number > 1 %}
                        <a href="{{ path_pagination }}{{ page_obj.number|add:'-1' }}">&laquo;</a>
                    {% endif %}
                    {% if page_obj.paginator.num_pages <= 1 %}
                        {{ pass }}
                    {% else %}
                        {% for i in page_obj.paginator.page_range %}
                            {% if page_obj.number == i %}
                                {{ i }}
                            {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                                <a href="{{ path_pagination }}{{ i }}">{{ i }}</a>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    {% if page_obj.paginator.num_pages > page_obj.number %}
                        <a href="{{ path_pagination }}{{ page_obj.number|add:'1' }}">&raquo;</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        <div id="form-person-search" data-is_valid="{{ form.is_valid }}" class="row container-card-style-2 display-none">
            <form class="form-style" action="" method="GET">
                <div class="row">
                    <div class="col-6">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="col-6">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                </div>
                <div class="row row-margin-style">
                    <div class="col-12 right-style">
                        <button type="submit" class="btn button-style">Szukaj</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="container-card-style-2">
            <table class="table table-style">
                <tbody>
                    {% for person in person_list %}
                        <tr>
                            <td class="col-1"><img src="{{ person.avatar.url }}"></td>
                            <td class="col-6"><a href="{% url 'person-detail' pk=person.pk %}" class="font-size-1-25">{{ person }}</a></td>
                            <td class="col-5 text-center">{{ person.country.name }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

movie_app/templates/movie_app/user_comments.html
{% extends 'movie_app/base.html' %}
{% block content %}
<div class="row container-body-style">
    <div class="container-header-style">{{ request.user.get_full_name }}</div>
    <div class="row">
        <div class="col-sm-2">
            <div class="container-image-style">
                <a href="{{ request.user.avatar.url }}"><img src="{{ request.user.avatar.url }}" alt="Avatar"></a>
            </div>
        </div>
        <div class="col-sm-10">
            <div class="container-card-style">
                <div class="row">
                    <div class="col-8 font-size-1-5">
                        Komentarze filmów ( {{ user.user_comments.count }} )
                    </div>
                    <div class="col-4 font-size-1-5 right-style">
                        {% if is_paginated %}
                            {% if page_obj.number > 1 %}
                                <a href="?page={{ page_obj.number|add:'-1' }}">&laquo;</a>
                            {% endif %}
                            {% if page_obj.paginator.num_pages <= 1 %}
                                {{ pass }}
                            {% else %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        {{ i }}
                                    {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                                        <a href="?page={{ i }}">{{ i }}</a>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                            {% if page_obj.paginator.num_pages > page_obj.number %}
                                <a href="?page={{ page_obj.number|add:'1' }}">&raquo;</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                <table class="table table-comment-style">
                    <tbody>
                        {% for comment in comment_list %}
                            <tr>
                                <td class="col-1"><img src="{{ comment.movie.avatar.url }}" alt="Avatar"></td>
                                <td class="col-11">
                                    <div class="row comment-header-style">
                                        <div class="col-10">
                                            <a href="{% url 'movie-detail' pk=comment.movie.pk %}">{{ comment.movie }}</a>
                                            {{ comment.date_added|date:"j E Y, H:i"}}
                                        </div>
                                        <div class="col-2 right-style">
                                            <a href="{% url 'user-comment-delete' pk=comment.pk %}?next={{ request.path }}#comments"
                                            class="text-danger" title="Usuń komentarz">&#10008;</a>
                                        </div>
                                    </div>
                                    <div class="text-comment-style">
                                        <span class="text-content">{{ comment.comment }}</span>
                                        <span class="text-hidden display-none"></span>
                                        <span class="dots display-none"> ...</span>
                                        <button class="button-more-style button-more display-none" title="Rozwiń tekst">&#8681;</button>
                                        <button class="button-more-style button-less display-none" title="Zwin tekst">&#8679;</button>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}